apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: echoservice2
  name: echoservice
  labels:
    app: echoservice
    provider: manifest
    foo: bar
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 50%
  replicas: 3
  template:
    metadata:
      labels:
        app: echoservice
    spec:
      containers:
      - name: echoservice
        image: dtan4/echoservice:latest
        ports:
        - containerPort: 8080
